INSERT INTO users (username, name, email, password, role, created_at) VALUES ('eduardo', 'Eduardo García', 'eduardo@example.com', 'password123', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('maria', 'María López', 'maria@example.com', 'password456', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('carlos', 'Carlos Ruiz', 'carlos@example.com', 'password789', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('ana', 'Ana Martínez', 'ana@example.com', 'password101', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('luis', 'Luis Fernández', 'luis@example.com', 'password202', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('sofia', 'Sofia Ramírez', 'sofia@example.com', 'password303', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('diego', 'Diego Torres', 'diego@example.com', 'password404', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('valentina', 'Valentina Morales', 'valentina@example.com', 'password505', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('javier', 'Javier Herrera', 'javier@example.com', 'password606', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('isabella', 'Isabella Castro', 'isabella@example.com', 'password707', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('andres', 'Andrés Vargas', 'andres@example.com', 'password808', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('scamila', 'Camila Mendoza', 'camila@example.com', 'password909', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('miguel', 'Miguel Ángel Pérez', 'miguel@example.com', 'password111', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('lucia', 'Lucía Romero', 'lucia@example.com', 'password222', 'USER', CURRENT_TIMESTAMP);
INSERT INTO users (username, name, email, password, role, created_at) VALUES ('gabriel', 'Gabriel Silva', 'gabriel@example.com', 'password333', 'ADMIN', CURRENT_TIMESTAMP);

INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Cyberpunk 2077: Phantom Liberty', 'Una expansión épica que lleva la historia de Cyberpunk a nuevas alturas con mecánicas mejoradas y gráficos de última generación. Explora una nueva zona con personajes fascinantes y misiones emocionantes.', 'Expansión épica con gráficos de última generación', 'CD Projekt Red', 'CD Projekt', '2025-11-15', 9.5, 'RPG', 'PC, PS5, Xbox Series X', 'Noviembre 2025', '#ef4444', true, 1250, 850);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Starfield: Extended Universe', 'Explora el universo infinito con nuevas mecánicas de exploración espacial y misiones proceduralmente generadas. Un viaje épico por las estrellas te espera.', 'Explora el universo infinito', 'Bethesda Game Studios', 'Bethesda Softworks', '2025-11-01', 9.2, 'RPG/Aventura', 'PC, Xbox Series X', '¡Recién salido!', '#10b981', true, 2100, 1500);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('The Last Guardian: Remastered', 'El clásico regresa con gráficos 4K HDR, ray tracing y nuevas características. Revive la magia de esta obra maestra con controles mejorados.', 'El clásico regresa en 4K HDR', 'Team Ico', 'Sony Interactive Entertainment', '2025-12-10', 9.8, 'Aventura', 'PS5, PC', 'Diciembre 2025', '#7c3aed', true, 980, 450);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Elden Ring: Shadow of the Erdtree', 'La expansión definitiva del aclamado Elden Ring trae nuevas áreas, jefes desafiantes y armas legendarias. Sumérgete en un mundo oscuro lleno de misterios.', 'Expansión definitiva de Elden Ring', 'FromSoftware', 'Bandai Namco', '2025-11-20', 9.7, 'Action RPG', 'PC, PS5, Xbox Series X', 'Próximamente', '#f59e0b', true, 3200, 2100);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Hollow Knight: Silksong', 'La esperada secuela de Hollow Knight presenta a Hornet en su propia aventura. Explora un nuevo reino con mecánicas de combate mejoradas.', 'Secuela de Hollow Knight con Hornet', 'Team Cherry', 'Team Cherry', '2025-12-01', 9.6, 'Metroidvania', 'PC, Nintendo Switch, PS5, Xbox Series X', 'Muy esperado', '#10b981', true, 2800, 1800);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('GTA VI', 'Regresa a Vice City en la entrega más ambiciosa de la saga Grand Theft Auto. Dos protagonistas, un mapa masivo y una historia épica de crimen y redención.', 'GTA regresa a Vice City en 2026', 'Rockstar North', 'Rockstar Games', '2026-03-15', 9.9, 'Action/Aventura', 'PC, PS5, Xbox Series X', '2026', '#ef4444', true, 5000, 0);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('The Legend of Zelda: Tears of the Kingdom', 'Continúa la aventura de Link en Hyrule con nuevas mecánicas de construcción y exploración vertical. Descubre islas flotantes y mazmorras desafiantes.', 'Nueva aventura épica de Link', 'Nintendo EPD', 'Nintendo', '2023-05-12', 9.8, 'Aventura/Acción', 'Nintendo Switch', 'Mejor del año', '#3b82f6', true, 4200, 3500);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Resident Evil 4 Remake', 'El survival horror clásico reimaginado con gráficos modernos y jugabilidad actualizada. León Kennedy regresa a la aldea española en una misión de rescate.', 'RE4 reimaginado para nueva generación', 'Capcom', 'Capcom', '2023-03-24', 9.4, 'Survival Horror', 'PC, PS5, Xbox Series X', 'Remake épico', '#dc2626', true, 3800, 2900);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Street Fighter 6', 'La nueva generación de peleas llega con gráficos revolucionarios y el innovador sistema Drive. Domina el World Tour y conviértete en campeón.', 'Nueva era de Street Fighter', 'Capcom', 'Capcom', '2023-06-02', 9.1, 'Lucha', 'PC, PS5, Xbox Series X', 'Top peleas', '#f59e0b', false, 2400, 1800);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Final Fantasy XVI', 'Una épica historia de venganza y redención con combate en tiempo real. Clive Rosfield busca venganza en un mundo de Eikons y magia oscura.', 'Épica de acción y fantasía', 'Square Enix', 'Square Enix', '2023-06-22', 9.3, 'Action RPG', 'PS5, PC', 'JRPG épico', '#8b5cf6', true, 3600, 2700);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Spider-Man 2', 'Peter Parker y Miles Morales unen fuerzas contra Venom y Kraven. Nueva York nunca fue tan peligrosa ni tan divertida de explorar.', 'Dos Spider-Men, doble acción', 'Insomniac Games', 'Sony Interactive', '2023-10-20', 9.6, 'Acción/Aventura', 'PS5', 'Exclusivo PS5', '#ef4444', true, 4800, 3200);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Baldurs Gate 3', 'La revolución del RPG con infinitas posibilidades. Crea tu héroe, reúne tu grupo y salva Faerûn de la amenaza de los Illithid.', 'RPG definitivo con D&D', 'Larian Studios', 'Larian Studios', '2023-08-03', 9.7, 'RPG', 'PC, PS5, Xbox Series X', 'GOTY 2023', '#10b981', true, 5200, 4100);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Alan Wake 2', 'El thriller psicológico regresa con dos protagonistas. Saga Anderson y Alan Wake luchan contra la oscuridad en esta obra maestra del terror.', 'Terror psicológico definitivo', 'Remedy Entertainment', 'Epic Games', '2023-10-27', 9.4, 'Survival Horror', 'PC, PS5, Xbox Series X', 'Horror 2023', '#7c3aed', true, 3100, 2300);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Hogwarts Legacy', 'Vive tu propia aventura en el mundo mágico de Harry Potter. Asiste a Hogwarts en 1890 y descubre secretos antiguos en este RPG de mundo abierto.', 'Tu aventura mágica en Hogwarts', 'Avalanche Software', 'Warner Bros', '2023-02-10', 8.9, 'RPG/Aventura', 'PC, PS5, Xbox Series X, Nintendo Switch', 'Mundo mágico', '#f59e0b', false, 4500, 3800);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Diablo IV', 'El infierno se desata en Sanctuary. Explora un mundo abierto oscuro y enfréntate a hordas demoníacas en el RPG de acción definitivo.', 'El infierno regresa a Sanctuary', 'Blizzard Entertainment', 'Blizzard Entertainment', '2023-06-06', 8.8, 'Action RPG', 'PC, PS5, Xbox Series X', 'Hack & Slash', '#dc2626', false, 3900, 3100);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Forza Motorsport', 'La simulación de carreras más realista regresa completamente reconstruida. 500 coches reales en pistas icónicas con física revolucionaria.', 'Simulación de carreras definitiva', 'Turn 10 Studios', 'Xbox Game Studios', '2023-10-10', 8.7, 'Racing', 'PC, Xbox Series X', 'Racing 2023', '#3b82f6', false, 2200, 1600);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Lies of P', 'Un souls-like inspirado en Pinocho con combate desafiante y atmósfera oscura. Pinocho debe convertirse en humano sobreviviendo a Belle Époque.', 'Pinocho como nunca lo viste', 'Neowiz', 'Neowiz', '2023-09-19', 8.6, 'Souls-like', 'PC, PS5, Xbox Series X', 'Souls 2023', '#8b5cf6', false, 1900, 1400);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Armored Core VI: Fires of Rubicon', 'FromSoftware regresa a sus raíces con mechas personalizables y combate frenético. Domina tu AC y lucha por el control de Rubicon.', 'Mechas de FromSoftware', 'FromSoftware', 'Bandai Namco', '2023-08-25', 8.9, 'Acción/Mecha', 'PC, PS5, Xbox Series X', 'Mecha 2023', '#f59e0b', false, 2600, 1900);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Dead Space Remake', 'El terror espacial clásico renace con gráficos impresionantes y mejoras en la jugabilidad. Isaac Clarke vuelve al Ishimura en esta pesadilla renovada.', 'Terror espacial renovado', 'Motive Studio', 'Electronic Arts', '2023-01-27', 9.0, 'Survival Horror', 'PC, PS5, Xbox Series X', 'Horror espacial', '#dc2626', false, 2800, 2100);
INSERT INTO games (title, description, short_description, developer, publisher, release_date, rating, genre, platforms, badge, badge_color, is_featured, view_count, download_count) VALUES ('Tekken 8', 'La saga King of Iron Fist regresa con gráficos next-gen y el sistema Heat. Peleas épicas con tu roster favorito en escenarios espectaculares.', 'Nueva era de Tekken', 'Bandai Namco', 'Bandai Namco', '2024-01-26', 9.2, 'Lucha', 'PC, PS5, Xbox Series X', 'Fighter 2024', '#ef4444', false, 3300, 2500);

-- Anime data
INSERT INTO animes (title_japanese, title_romaji, title_english, synopsis, poster_url, banner_url, genres, type, total_episodes, status, release_date, studio, rating, view_count, favorite_count, is_featured) VALUES 
('鬼滅の刃', 'Kimetsu no Yaiba', 'Demon Slayer', 'Tanjiro Kamado se convierte en cazador de demonios tras el asesinato de su familia y la transformación de su hermana Nezuko en demonio. Busca una cura mientras lucha contra poderosos demonios.', 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg', null, 'Acción,Shonen,Fantasía,Histórico', 'TV', 26, 'FINISHED', '2019-04-06', 'Ufotable', 9.5, 15000, 8500, true);

INSERT INTO animes (title_japanese, title_romaji, title_english, synopsis, poster_url, banner_url, genres, type, total_episodes, status, release_date, studio, rating, view_count, favorite_count, is_featured) VALUES 
('進撃の巨人', 'Shingeki no Kyojin', 'Attack on Titan', 'La humanidad vive encerrada tras enormes muros para protegerse de los titanes que devoran humanos. Eren Yeager jura exterminarlos a todos después de que uno destruya su ciudad natal.', 'https://cdn.myanimelist.net/images/anime/10/47347.jpg', null, 'Acción,Drama,Shonen,Misterio', 'TV', 25, 'FINISHED', '2013-04-07', 'MAPPA', 9.7, 18500, 12000, true);

INSERT INTO animes (title_japanese, title_romaji, title_english, synopsis, poster_url, banner_url, genres, type, total_episodes, status, release_date, studio, rating, view_count, favorite_count, is_featured) VALUES 
('呪術廻戦', 'Jujutsu Kaisen', 'Jujutsu Kaisen', 'Yuji Itadori se une a una escuela de hechicería para controlar la maldición que porta dentro de sí. Junto a sus compañeros, enfrenta maldiciones mortales mientras descubre secretos oscuros.', 'https://cdn.myanimelist.net/images/anime/1171/109222.jpg', null, 'Acción,Shonen,Sobrenatural,Fantasía', 'TV', 24, 'AIRING', '2020-10-03', 'MAPPA', 9.3, 14200, 9500, true);

INSERT INTO animes (title_japanese, title_romaji, title_english, synopsis, poster_url, banner_url, genres, type, total_episodes, status, release_date, studio, rating, view_count, favorite_count, is_featured) VALUES 
('ワンピース', 'One Piece', 'One Piece', 'Monkey D. Luffy y su tripulación de piratas buscan el tesoro legendario One Piece para convertirse en el Rey de los Piratas. Una aventura épica llena de acción, comedia y emociones.', 'https://cdn.myanimelist.net/images/anime/6/73245.jpg', null, 'Acción,Aventura,Shonen,Fantasía', 'TV', 1000, 'AIRING', '1999-10-20', 'Toei Animation', 9.4, 25000, 15000, true);

INSERT INTO animes (title_japanese, title_romaji, title_english, synopsis, poster_url, banner_url, genres, type, total_episodes, status, release_date, studio, rating, view_count, favorite_count, is_featured) VALUES 
('君の名は', 'Kimi no Na wa', 'Your Name', 'Mitsuha y Taki intercambian cuerpos misteriosamente. A medida que sus vidas se entrelazan, descubren una conexión que trasciende el tiempo y el espacio en esta historia de amor conmovedora.', 'https://cdn.myanimelist.net/images/anime/5/87048.jpg', null, 'Romance,Drama,Sobrenatural', 'MOVIE', 1, 'FINISHED', '2016-08-26', 'CoMix Wave Films', 9.8, 20000, 18000, true);

INSERT INTO animes (title_japanese, title_romaji, title_english, synopsis, poster_url, banner_url, genres, type, total_episodes, status, release_date, studio, rating, view_count, favorite_count, is_featured) VALUES 
('僕のヒーローアカデミア', 'Boku no Hero Academia', 'My Hero Academia', 'En un mundo donde el 80% de la población tiene superpoderes, Izuku Midoriya nace sin ellos. Pero su determinación lo lleva a heredar el poder del héroe más grande, All Might.', 'https://cdn.myanimelist.net/images/anime/10/78745.jpg', null, 'Acción,Shonen,Superhéroes', 'TV', 13, 'FINISHED', '2016-04-03', 'Bones', 9.1, 16800, 11200, true);

INSERT INTO animes (title_japanese, title_romaji, title_english, synopsis, poster_url, banner_url, genres, type, total_episodes, status, release_date, studio, rating, view_count, favorite_count, is_featured) VALUES 
('ハイキュー!!', 'Haikyuu!!', 'Haikyu!!', 'Hinata Shoyo sueña con convertirse en un gran jugador de voleibol a pesar de su baja estatura. Se une al equipo de Karasuno High donde encontrará rivales y aliados inesperados.', 'https://cdn.myanimelist.net/images/anime/7/76014.jpg', null, 'Deportes,Shonen,Comedia,Drama', 'TV', 25, 'FINISHED', '2014-04-06', 'Production I.G', 9.2, 13500, 9800, false);

INSERT INTO animes (title_japanese, title_romaji, title_english, synopsis, poster_url, banner_url, genres, type, total_episodes, status, release_date, studio, rating, view_count, favorite_count, is_featured) VALUES 
('ヴァイオレット・エヴァーガーデン', 'Violet Evergarden', 'Violet Evergarden', 'Violet, ex-soldado, se convierte en escritora de cartas para entender el significado de las últimas palabras de su comandante: "Te amo". Un viaje emocional sobre el amor y la pérdida.', 'https://cdn.myanimelist.net/images/anime/1795/95088.jpg', null, 'Drama,Fantasía,Slice of Life', 'TV', 13, 'FINISHED', '2018-01-11', 'Kyoto Animation', 9.6, 11200, 10500, true);

INSERT INTO animes (title_japanese, title_romaji, title_english, synopsis, poster_url, banner_url, genres, type, total_episodes, status, release_date, studio, rating, view_count, favorite_count, is_featured) VALUES 
('東京喰種', 'Tokyo Ghoul', 'Tokyo Ghoul', 'Ken Kaneki se convierte en medio-ghoul tras un encuentro fatal. Atrapado entre dos mundos, debe aprender a sobrevivir mientras mantiene su humanidad en un Tokyo oscuro y peligroso.', 'https://cdn.myanimelist.net/images/anime/5/64449.jpg', null, 'Acción,Horror,Seinen,Sobrenatural', 'TV', 12, 'FINISHED', '2014-07-04', 'Pierrot', 8.8, 14800, 8900, false);

INSERT INTO animes (title_japanese, title_romaji, title_english, synopsis, poster_url, banner_url, genres, type, total_episodes, status, release_date, studio, rating, view_count, favorite_count, is_featured) VALUES 
('フリーレン', 'Sousou no Frieren', 'Frieren: Beyond Journeys End', 'Tras derrotar al Rey Demonio, la elfa Frieren reflexiona sobre su largo viaje con sus compañeros humanos. Mil años después, emprende un nuevo viaje para entender mejor a la humanidad y sus conexiones.', 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg', null, 'Fantasía,Drama,Aventura', 'TV', 28, 'AIRING', '2023-09-29', 'Madhouse', 9.7, 12500, 11800, true);

-- Episodes for Demon Slayer (Kimetsu no Yaiba)
INSERT INTO episodes (anime_id, episode_number, title, description, duration, release_date, view_count) VALUES 
(1, 1, 'Crueldad', 'Tanjiro regresa a casa para encontrar a su familia masacrada por demonios. Su hermana Nezuko sobrevive pero se ha convertido en demonio.', 24, '2019-04-06', 8500);

INSERT INTO episodes (anime_id, episode_number, title, description, duration, release_date, view_count) VALUES 
(1, 2, 'El maestro Sakonji Urokodaki', 'Tanjiro conoce a Giyu Tomioka, un Demon Slayer que lo envía con Sakonji Urokodaki para entrenar.', 24, '2019-04-13', 7200);

INSERT INTO episodes (anime_id, episode_number, title, description, duration, release_date, view_count) VALUES 
(1, 3, 'Sabito y Makomo', 'Durante su entrenamiento, Tanjiro conoce a dos misteriosos jóvenes que lo ayudan a mejorar sus habilidades.', 24, '2019-04-20', 6800);

-- Episodes for Attack on Titan
INSERT INTO episodes (anime_id, episode_number, title, description, duration, release_date, view_count) VALUES 
(2, 1, 'A ti, dentro de 2000 años', 'Un titán colosal rompe el muro Maria, permitiendo que los titanes invadan. La madre de Eren es devorada frente a sus ojos.', 24, '2013-04-07', 12000);

INSERT INTO episodes (anime_id, episode_number, title, description, duration, release_date, view_count) VALUES 
(2, 2, 'Ese día', 'Eren jura venganza y se une al ejército junto a Mikasa y Armin para entrenar y convertirse en soldados.', 24, '2013-04-14', 10500);

-- Episodes for Jujutsu Kaisen
INSERT INTO episodes (anime_id, episode_number, title, description, duration, release_date, view_count) VALUES 
(3, 1, 'Ryomen Sukuna', 'Yuji Itadori se traga un dedo maldito para salvar a sus amigos, convirtiéndose en el recipiente del poderoso Ryomen Sukuna.', 24, '2020-10-03', 9800);

INSERT INTO episodes (anime_id, episode_number, title, description, duration, release_date, view_count) VALUES 
(3, 2, 'Para mí', 'Yuji se une a Tokyo Jujutsu High y conoce a Megumi Fushiguro y Nobara Kugisaki.', 24, '2020-10-10', 8900);

-- Episodes for Your Name (Movie)
INSERT INTO episodes (anime_id, episode_number, title, description, duration, release_date, view_count) VALUES 
(5, 1, 'Your Name', 'Mitsuha y Taki intercambian cuerpos inexplicablemente, viviendo las vidas del otro mientras buscan descubrir el misterio detrás de su conexión.', 106, '2016-08-26', 18500);

